name: Banking Project CI/CD Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for GH Pages action

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
            
      - name: Build and Test with Allure
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          mvn clean test -Dtest.env=$TEST_ENV -Dapi.key=$API_KEY \
          -Dallure.results.directory=target/allure-results \
          -Dcucumber.plugin="io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm, html:target/cucumber-reports.html"
          
      - name: Generate Allure Report
        run: |
          mvn allure:report -Dallure.results.directory=target/allure-results
          
      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            target/surefire-reports
            target/allure-results
            
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: target/screenshots

  upload-reports:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # Checkout the gh-pages branch if it exists

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          force_orphan: true
