name: Banking Project CI/CD Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f0dffe99f0961f9e83 # v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v3.3.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and Test
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}
          API_KEY: ${{ secrets.API_KEY }}
        run: mvn clean test -Dtest.env=$TEST_ENV -Dapi.key=$API_KEY -Dallure.results.directory=target/allure-results

      - name: Generate Cucumber HTML Report
        run: mvn io.qameta.allure:cucumber7-jvm:report

      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven:report -Dallure.results.directory=target/allure-results

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@5076952e7b4c4e7e4f8857290f3d2f1e5475b7f4 # v4.3.0
        with:
          name: test-logs
          path: target/surefire-reports

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@5076952e7b4c4e7e4f8857290f3d2f1e5475b7f4 # v4.3.0
        with:
          name: test-screenshots
          path: target/screenshots

  upload-reports:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.0

      - name: Upload Allure Report
        uses: actions/upload-artifact@5076952e7b4c4e7e4f8857290f3d2f1e5475b7f4 # v4.3.0
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@5076952e7b4c4e7e4f8857290f3d2f1e5475b7f4 # v4.3.0
        with:
          name: cucumber-report
          path: target/cucumber-reports

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin

      - name: Notify Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@6c6629d2d2520b3664245a7f65fe80f838650a68 # v1.23.0
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: 'your-channel'
          text: 'Test failures detected in Banking Project CI/CD. Check Allure report.'
